// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Вадим\Desktop\geo-microservices\geo\service\service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	suggest "github.com/ekomobile/dadata/v2/api/suggest"
	gomock "github.com/golang/mock/gomock"
)

// MockApi is a mock of Api interface.
type MockApi struct {
	ctrl     *gomock.Controller
	recorder *MockApiMockRecorder
}

// MockApiMockRecorder is the mock recorder for MockApi.
type MockApiMockRecorder struct {
	mock *MockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *MockApi {
	mock := &MockApi{ctrl: ctrl}
	mock.recorder = &MockApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApi) EXPECT() *MockApiMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockApi) Address(ctx context.Context, params *suggest.RequestParams) ([]*suggest.AddressSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address", ctx, params)
	ret0, _ := ret[0].([]*suggest.AddressSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Address indicates an expected call of Address.
func (mr *MockApiMockRecorder) Address(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockApi)(nil).Address), ctx, params)
}
